### ISSUE TITLE
runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by coopliu** [jamespwilliams/dns-over-icmp#2]
When I run sudo./pingdns, it displays:

anic: runtime error: slice bounds out of range [16:0]

goroutine 1 [running]:
github.com/jamespwilliams/dns-over-ping.Server.handleICMPEcho({0x640, {0x5bcfb8, 0x8}, {0x5bc9a6, 0x7}, 0xc0000cc0e0}, 0xc0000f6000?)
        /root/dns-over-ping/pingdns.go:106 +0x605
github.com/jamespwilliams/dns-over-ping.Server.handleBytes({0x640, {0x5bcfb8, 0x8}, {0x5bc9a6, 0x7}, 0xc0000cc0e0}, {0xc0000f6000?, 0x1?, 0x0?})
        /root/dns-over-ping/pingdns.go:97 +0x10c
github.com/jamespwilliams/dns-over-ping.Server.Serve({0x640, {0x5bcfb8, 0x8}, {0x5bc9a6, 0x7}, 0xc0000cc0e0})
        /root/dns-over-ping/pingdns.go:64 +0x1ec
main.main()
        /root/dns-over-ping/cmd/pingdns/main.go:25 +0x245

**Comment by PolarPeak** [comment]
Me too
panic: runtime error: slice bounds out of range [16:0]

goroutine 1 [running]:
github.com/jamespwilliams/dns-over-ping.Server.handleICMPEcho({0x640, {0x5a0ad8, 0x8}, {0x5a04dc, 0x7}, 0xc0000f60e0}, 0xc000120000)
        /root/dns-over-ping-main/pingdns.go:106 +0x268
github.com/jamespwilliams/dns-over-ping.Server.handleBytes({0x640, {0x5a0ad8, 0x8}, {0x5a04dc, 0x7}, 0xc0000f60e0}, {0xc000120000, 0x1, 0x0})
        /root/dns-over-ping-main/pingdns.go:97 +0x10c
github.com/jamespwilliams/dns-over-ping.Server.Serve({0x640, {0x5a0ad8, 0x8}, {0x5a04dc, 0x7}, 0xc0000f60e0})
        /root/dns-over-ping-main/pingdns.go:64 +0x1ec
main.main()
        /root/dns-over-ping-main/cmd/pingdns/main.go:25 +0x24c
[root@iZ2vc79qc6ja2gvnerg92gZ dns-over-ping-main]# ./pingdns 
panic: runtime error: slice bounds out of range [16:0]

goroutine 1 [running]:
github.com/jamespwilliams/dns-over-ping.Server.handleICMPEcho({0x640, {0x5a0ad8, 0x8}, {0x5a04dc, 0x7}, 0xc0000f60e0}, 0xc000120000)
        /root/dns-over-ping-main/pingdns.go:106 +0x268
github.com/jamespwilliams/dns-over-ping.Server.handleBytes({0x640, {0x5a0ad8, 0x8}, {0x5a04dc, 0x7}, 0xc0000f60e0}, {0xc000120000, 0x1, 0x0})
        /root/dns-over-ping-main/pingdns.go:97 +0x10c
github.com/jamespwilliams/dns-over-ping.Server.Serve({0x640, {0x5a0ad8, 0x8}, {0x5a04dc, 0x7}, 0xc0000f60e0})
        /root/dns-over-ping-main/pingdns.go:64 +0x1ec
main.main()
        /root/dns-over-ping-main/cmd/pingdns/main.go:25 +0x24c

**Comment by jamespwilliams** [comment]
Interesting, looks like the server is receiving an ICMP echo request packet with a short body on your machines - I don't know why that would be happening. Anyway, https://github.com/jamespwilliams/dns-over-ping/commit/523dc546cf40374e492b832d0c9bb19fa59cae24 should stop the panic happening in this case, let me know if it works for you now.

**Comment by coopliu** [comment]
I re-git clone, compile and execute, and it says:


[root@VM-20-8-centos dns-over-ping]# sudo ./pingdns
2022-11-15T10:33:04.150+0800    WARN    dns-over-ping/pingdns.go:66     failed to handle request        {"error": "icmp echo data was too short? got 0 bytes, expected at least 16"}
github.com/jamespwilliams/dns-over-ping.Server.Serve
        /root/xxx/dns-over-ping/pingdns.go:66
main.main
        /root/xxx/dns-over-ping/cmd/pingdns/main.go:25
runtime.main
        /usr/local/go/src/runtime/proc.go:255
2022-11-15T10:33:05.172+0800    WARN    dns-over-ping/pingdns.go:66     failed to handle request        {"error": "icmp echo data was too short? got 0 bytes, expected at least 16"}
github.com/jamespwilliams/dns-over-ping.Server.Serve
        /root/xxx/dns-over-ping/pingdns.go:66
main.main
        /root/xxx/dns-over-ping/cmd/pingdns/main.go:25
runtime.main
